apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: Starwars Quote
spec:
  replicas: 2
  template:
    metadata:
      labels:
        editor: vscode
    spec:
      containers:
      - name: starwarsquote
        image: aks01acr.azurecr.io/starwarsquote:__TAG__